<?php

namespace Database\Seeders;

use App\Models\EmailTemplate;
use Illuminate\Database\Seeder;

class PinellasEmailTemplateSeeder extends Seeder
{
    public function run()
    {
        $templates = [
            // MFA / Security Gate Templates
            [
                'name' => 'Email Verification',
                'code' => 'email_verification',
                'subject' => 'Verify Your Email Address - Pinellas Federal Credit Union',
                'title' => 'Email Verification Required',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => 'Welcome to Pinellas Federal Credit Union. To ensure the security of your account and activate your full digital banking features, please verify your email address. This step helps us protect your sensitive financial information.',
                'button_level' => 'Verify My Email',
                'button_link' => '[[token]]',
                'footer_body' => 'Secure Banking, Simplified.',
            ],
            [
                'name' => 'Generic OTP',
                'code' => 'otp',
                'subject' => 'Your Security Code: [[otp_code]]',
                'title' => 'Identity Verification',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => 'For your security, we require a verification code to authorize the following action: <strong>[[action]]</strong>.<br><br><div style="text-align:center; font-size: 32px; font-weight: bold; color: #00549b; letter-spacing: 5px; padding: 20px; background: #f8fafc; border-radius: 8px; margin: 20px 0;">[[otp_code]]</div><br>This code is valid for a single use only. If you did not initiate this request, please contact our security team immediately.',
                'footer_body' => 'Pinellas FCU Security Team',
            ],
            [
                'name' => 'MFA Generic OTP',
                'code' => 'mfa_otp',
                'subject' => 'Authorization Code: [[otp_code]]',
                'title' => 'Security Authorization',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'To complete your requested action (<strong>[[action]]</strong>), please enter the authorization code provided below:<br><br><div style="text-align:center; font-size: 32px; font-weight: bold; color: #00549b; letter-spacing: 5px; padding: 20px; background: #f8fafc; border-radius: 8px; margin: 20px 0;">[[otp_code]]</div><br>This code will expire in 10 minutes. <strong>Pinellas FCU will never ask for this code over the phone or via text.</strong>',
                'footer_body' => 'Always Secure. Always Pinellas.',
            ],
            [
                'name' => 'MFA Transfer Verification',
                'code' => 'mfa_transfer',
                'for' => 'User',
                'subject' => 'Verify Your Fund Transfer - [[otp_code]]',
                'title' => 'Transfer Authorization',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'You are initiating a fund transfer. Please enter the following authorization code to confirm this transaction:<br><br><div style="text-align:center; font-size: 32px; font-weight: bold; color: #00549b; letter-spacing: 5px; padding: 20px; background: #f8fafc; border-radius: 8px; margin: 20px 0;">[[otp_code]]</div><br>If this was not you, please log in to your account and change your security settings immediately.',
                'button_level' => 'Secure My Account',
                'button_link' => '[[site_url]]/user/settings/security',
                'footer_body' => 'Pinellas Credit Union Member Support',
            ],
            [
                'name' => 'MFA Withdrawal Verification',
                'code' => 'mfa_withdrawal',
                'for' => 'User',
                'subject' => 'Confirm Your Withdrawal Request - [[otp_code]]',
                'title' => 'Withdrawal Authorization',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'We received a request to withdraw funds from your account. To ensure this request is authorized, please provide the following security code:<br><br><div style="text-align:center; font-size: 32px; font-weight: bold; color: #da291c; letter-spacing: 5px; padding: 20px; background: #fff5f5; border-radius: 8px; margin: 20px 0;">[[otp_code]]</div><br>This extra step helps us keep your hard-earned money safe.',
                'footer_body' => 'Pinellas Credit Union | Your Security is Our Priority',
            ],
            [
                'name' => 'MFA Profile Update',
                'code' => 'mfa_profile_update',
                'for' => 'User',
                'subject' => 'Verify Profile Change - [[otp_code]]',
                'title' => 'Security: Profile Update',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => 'A change has been requested to your sensitive profile information (such as your email or username). Please use the code below to verify this change:<br><br><div style="text-align:center; font-size: 32px; font-weight: bold; color: #00549b; letter-spacing: 5px; padding: 20px; background: #f8fafc; border-radius: 8px; margin: 20px 0;">[[otp_code]]</div><br>If you did not request this change, please secure your account immediately.',
                'button_level' => 'Change Password',
                'button_link' => '[[site_url]]/user/settings/security',
                'footer_body' => 'Helping you grow and protect your wealth.',
            ],
            [
                'name' => 'MFA Security Change',
                'code' => 'mfa_security_change',
                'for' => 'User',
                'subject' => 'Authorize Security Setting Change - [[otp_code]]',
                'title' => 'Authorization Required',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'You are updating your security settings (Password or PIN). To confirm this action, please enter the following code:<br><br><div style="text-align:center; font-size: 32px; font-weight: bold; color: #00549b; letter-spacing: 5px; padding: 20px; background: #f8fafc; border-radius: 8px; margin: 20px 0;">[[otp_code]]</div><br>Stay safe and secure.',
                'footer_body' => 'Team Pinellas Credit Union',
            ],
            [
                'name' => 'Forget Password',
                'code' => 'user_password_change',
                'subject' => 'Password Reset Request',
                'title' => 'Security: Password Update',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => 'We received a request to reset your digital banking password. To choose a new secure password, please click the button below. If you did not make this request, your account is still secure and you can safely ignore this email.',
                'button_level' => 'Set New Password',
                'button_link' => '[[token]]',
                'footer_body' => 'Your Security is Our Priority.',
            ],

            // Transaction / Account Activity Templates
            [
                'name' => 'Fund Transfer Request',
                'code' => 'fund_transfer_request',
                'subject' => 'Transfer Notification: [[status]]',
                'title' => 'Transaction Status Update',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'This is an official notification regarding your recent fund transfer request for <strong>[[amount]]</strong>. Your request status has been updated to: <strong>[[status]]</strong>.<br><br><strong>Transaction Details:</strong><br>Recipient: [[account_name]]<br>Account: [[account_number]]<br>Subtotal: [[amount]]<br>Deducted Amount: [[total_amount]]',
                'button_level' => 'View Activity',
                'button_link' => '[[site_url]]/user/dashboard',
                'footer_body' => 'Thank you for banking with Pinellas Federal Credit Union.',
            ],
            [
                'name' => 'Fund Transfer (Own Bank)',
                'code' => 'fund_transfer',
                'subject' => 'Transfer Confirmation: [[status]]',
                'title' => 'Transfer Status Update',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'Your internal transfer to account <strong>[[account_number]]</strong> ([[account_name]]) has been completed. Status: <strong>[[status]]</strong>.<br><br><strong>Summary:</strong><br>Amount: [[amount]]<br>Fee: [[charge]]<br>Total Deducted: [[total_amount]]',
                'footer_body' => 'Reliable. Secure. Pinellas.',
            ],
            [
                'name' => 'Wire Transfer Request',
                'code' => 'wire_transfer_request',
                'subject' => 'Wire Transfer Notification: [[status]]',
                'title' => 'Processing Request',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'We have received your wire transfer request for [[amount]]. The transaction is currently [[status]].',
                'footer_body' => 'Global Banking, Local Care.',
            ],
            [
                'name' => 'Wire Transfer (Result)',
                'code' => 'wire_transfer',
                'subject' => 'Wire Transfer Status: [[status]]',
                'title' => 'Wire Transfer Notification',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'We are writing to inform you that your wire transfer to <strong>[[account_number]]</strong> has been processed. Status: <strong>[[status]]</strong>.<br><br><strong>Summary:</strong><br>Amount: [[amount]]<br>Fee: [[charge]]<br>Total: [[total_amount]]',
                'footer_body' => 'Global Banking, Local Care.',
            ],
            [
                'name' => 'Manual Deposit request Action',
                'code' => 'user_manual_deposit_request',
                'subject' => 'Deposit Notification: [[status]]',
                'title' => 'Account Activity: Deposit',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => 'We are writing to update you on your recent deposit request. The transaction status is currently: <strong>[[status]]</strong>.<br><br><strong>Transaction Details:</strong><br>ID: [[txn]]<br>Gateway: [[gateway_name]]<br>Amount: [[deposit_amount]]<br><br>[[message]]',
                'button_level' => 'View My Account',
                'button_link' => '[[site_url]]/user/deposits/history',
                'footer_body' => 'Supporting Your Financial Growth.',
            ],
            [
                'name' => 'Withdraw Request Action',
                'code' => 'withdraw_request_user',
                'for' => 'User',
                'subject' => 'Withdrawal Notification: [[status]]',
                'title' => 'Account Activity: Withdrawal',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'This email is to inform you of a status update regarding your withdrawal request. Your request is currently: <strong>[[status]]</strong>.<br><br><strong>Transaction Details:</strong><br>Transaction ID: [[txn]]<br>Amount: [[withdraw_amount]]<br>Method: [[method_name]]<br><br>[[message]]',
                'button_level' => 'Review Transaction',
                'button_link' => '[[site_url]]/user/withdraw/history',
                'footer_body' => 'Committed to Your Financial Success.',
            ],

            // Lending / Plans
            [
                'name' => 'Loan Approved',
                'code' => 'loan_approved',
                'subject' => 'Loan Application Status: [[status]]',
                'title' => 'Lending Decision Notification',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'We are pleased to provide an update on your [[plan_name]] loan application. Your application has been updated to: <strong>[[status]]</strong>.<br><br><strong>Summary:</strong><br>Loan Amount: [[loan_amount]]<br>Installment Rate: [[installment_rate]]<br><br>Please log in to your dashboard to review the terms or complete any pending actions.',
                'button_level' => 'Review Loan Terms',
                'button_link' => '[[site_url]]/user/loan/list',
                'footer_body' => 'Empowering Your Dreams.',
            ],
            [
                'name' => 'Loan Rejected',
                'code' => 'loan_rejected',
                'for' => 'User',
                'subject' => 'Loan Application Update - [[plan_name]]',
                'title' => 'Lending Update',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'Your loan application status for the [[plan_name]] plan has been updated to <strong>[[status]]</strong>. <br><br>Amount: [[loan_amount]]<br><br>Please log in to your account for more information.',
                'footer_body' => 'Investing in your dreams.',
            ],
            [
                'name' => 'Loan Installment',
                'code' => 'loan_installment',
                'subject' => 'Loan Installment Processed',
                'title' => 'Lending Account Activity',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => 'Your loan installment for [[plan_name]] (#[[loan_id]]) has been processed.<br><br><strong>Transaction Details:</strong><br>Amount: [[installment_amount]]<br>Next Installment: [[next_installment_date]]',
                'footer_body' => 'Partnering in Your Financial Journey.',
            ],
            [
                'name' => 'Loan Installment Due',
                'code' => 'loan_installment_due',
                'subject' => 'Action Required: Loan Installment Due',
                'title' => 'Urgent: Lending Account Alert',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'A payment for your loan [[plan_name]] (#[[loan_id]]) is currently overdue or requires attention. Please ensure sufficient funds are available for processing.<br><br><strong>Details:</strong><br>Amount: [[installment_amount]]<br>Total Due: [[loan_amount]]',
                'footer_body' => 'Member Security & Success.',
            ],

            // Savings / DPS / FDR
            [
                'name' => 'DPS Opened',
                'code' => 'dps_opened',
                'for' => 'User',
                'subject' => 'DPS Savings Plan Opened - [[plan_name]]',
                'title' => 'Savings Account Created',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'You have successfully opened a <strong>[[plan_name]]</strong> DPS savings plan (#[[dps_id]]).<br><br><strong>Summary:</strong><br>Installment: [[per_installment]]<br>Interest Rate: [[interest_rate]]%<br>Total Installments: [[total_installment]]',
                'footer_body' => 'Saving for a brighter tomorrow.',
            ],
            [
                'name' => 'DPS Notification',
                'code' => 'dps_completed',
                'subject' => 'Savings Plan Notification: [[status]]',
                'title' => 'Savings Account Activity',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => 'We have an update regarding your <strong>[[plan_name]]</strong> savings plan. Activity has been recorded with the status: <strong>[[status]]</strong>.<br><br><strong>Activity Details:</strong><br>Plan Type: [[plan_name]]<br>Matured Amount/Balance: [[matured_amount]]<br><br>Check your dashboard for comprehensive savings history.',
                'button_level' => 'View Savings',
                'button_link' => '[[site_url]]/user/dps/list',
                'footer_body' => 'Building Your Future, One Step at a Time.',
            ],
            [
                'name' => 'DPS Installment Due',
                'code' => 'dps_installment_due',
                'subject' => 'Savings Alert: Installment Due',
                'title' => 'Savings Account Notification',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'Your installment for [[plan_name]] savings plan is now due. Ensuring consistent contributions helps you reach your financial goals faster.',
                'footer_body' => 'Secure Growth. Guaranteed.',
            ],
            [
                'name' => 'DPS Closed',
                'code' => 'dps_closed',
                'for' => 'User',
                'subject' => 'Savings Plan Notification',
                'title' => 'Account Update: [[plan_name]] Activity',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'There has been activity on your [[plan_name]] account. <br><br><strong>Details:</strong><br>Plan: [[plan_name]]<br>ID: [[dps_id]]<br>Status/Action: [[status]]<br>Matured Amount/Balance: [[matured_amount]]',
                'footer_body' => 'Helping you save for what matters.',
            ],
            [
                'name' => 'FDR Opened',
                'code' => 'fdr_opened',
                'subject' => 'FDR Subscription Successful',
                'title' => 'FDR Account Created',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'You have successfully subscribed to the <strong>[[plan_name]]</strong> FDR plan.<br><br><strong>Summary:</strong><br>Principal: [[amount]]<br>Interest Rate: [[interest_rate]]%<br>Term: [[installment_interval]] Days',
                'footer_body' => 'Integrity. Transparency. Growth.',
            ],
            [
                'name' => 'FDR Installment',
                'code' => 'fdr_installment',
                'subject' => 'FDR Interest Credited',
                'title' => 'FDR Account Activity',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'Interest for your FDR plan <strong>[[plan_name]]</strong> has been credited to your account balance.<br><br><strong>Details:</strong><br>Interest Credited: [[per_installment]]<br>Next Interest Date: [[next_installment_date]]',
                'footer_body' => 'Your Capital, Our Responsibility.',
            ],
            [
                'name' => 'FDR Completed',
                'code' => 'fdr_completed',
                'subject' => 'FDR Maturity Notification',
                'title' => 'FDR Account Matured',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'Your FDR plan <strong>[[plan_name]]</strong> has reached maturity. The principal and final interest have been successfully settled to your primary account balance.',
                'footer_body' => 'Thank You for Investing with Us.',
            ],
            [
                'name' => 'FDR Closed',
                'code' => 'fdr_closed',
                'subject' => 'FDR Account Closed',
                'title' => 'FDR Status Change',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => 'Your FDR plan <strong>[[plan_name]]</strong> (#[[fdr_id]]) has been closed upon request. Refunds have been processed as per the plan terms.',
                'footer_body' => 'Always Here to Help.',
            ],

            // Support / KYC / Misc User
            [
                'name' => 'User Account Disabled',
                'code' => 'user_account_disabled',
                'subject' => 'Important: Account Security Notification',
                'title' => 'Account Status Update',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'For your security and the protection of your assets, your digital banking access has been temporarily deactivated. This often occurs due to extended inactivity or for account verification purposes.<br><br>To restore your access, please contact our member support team or attempt to securely verify your identity through our portal.',
                'button_level' => 'Contact Support',
                'button_link' => '[[site_url]]/contact',
                'footer_body' => 'Integrity in Every Transaction.',
            ],
            [
                'name' => 'KYC Action',
                'code' => 'kyc_action',
                'subject' => 'Identity Verification Update',
                'title' => 'KYC / Proof of Identity',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'Your identity verification documents (KYC) have been reviewed. The current status of your verification is: <strong>[[status]]</strong>.<br><br>[[message]]',
                'button_level' => 'View Verification Status',
                'button_link' => '[[site_url]]/user/kyc',
                'footer_body' => 'Complying with Federal Regulations for Your Safety.',
            ],
            [
                'name' => 'Support Ticket Update',
                'code' => 'user_support_ticket',
                'subject' => 'Update: Support Ticket [[title]]',
                'title' => 'Support Request Update',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => 'We have an update regarding your support ticket: <strong>[[title]]</strong>.<br><br><strong>Current Status:</strong> [[status]]<br><br><strong>Message:</strong><br>[[message]]',
                'button_level' => 'View Support Ticket',
                'button_link' => '[[site_url]]/user/support-ticket',
                'footer_body' => 'We Are Here to Assist You.',
            ],
            [
                'name' => 'Portfolio Achieve',
                'code' => 'portfolio_achieve',
                'subject' => 'Congratulations: Portfolio Milestone Achieved',
                'title' => 'Membership Recognition',
                'salutation' => 'Dear [[full_name]]',
                'message_body' => 'Congratulations! You have achieved the <strong>[[portfolio_name]]</strong> status. This milestone reflects your continued trust and activity with Pinellas Federal Credit Union. We have applied your membership rewards to your account balance.',
                'footer_body' => 'Excellence in Membership.',
            ],
            [
                'name' => 'Get Rewards',
                'code' => 'get_rewards',
                'for' => 'User',
                'subject' => 'Congratulations! Rewards Earned',
                'title' => 'You Got Points!',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => 'Great news! You have just earned <strong>[[points]]</strong> reward points for your recent activity. Thank you for being an active member of Pinellas Credit Union.',
                'footer_body' => 'More rewards, more reasons to bank with us.',
            ],

            // Admin Notifications
            [
                'name' => 'Loan Application (Admin)',
                'code' => 'loan_apply',
                'for' => 'Admin',
                'subject' => 'New Loan Application Received',
                'title' => 'Lending Alert',
                'salutation' => 'Hi Admin',
                'message_body' => 'A new loan application has been submitted.<br><br>User: [[full_name]]<br>Plan: [[plan_name]]<br>Amount: [[loan_amount]]',
                'footer_body' => 'Lending Management System',
            ],
            [
                'name' => 'User Mail Send',
                'code' => 'user_mail',
                'for' => 'User',
                'subject' => '[[subject]]',
                'title' => 'Official Notification',
                'salutation' => 'Hello [[full_name]]',
                'message_body' => '[[message]]',
                'footer_body' => 'Pinellas Federal Credit Union',
            ],
            [
                'name' => 'Subscriber Mail Send',
                'code' => 'subscriber_mail',
                'for' => 'Subscriber',
                'subject' => '[[subject]] for [[full_name]]',
                'title' => 'Welcome to [[site_title]]',
                'salutation' => 'Hi [[full_name]]',
                'message_body' => '[[message]]<br><br>Find out more at [[site_url]]',
                'footer_body' => 'Thanks for joining our platform!',
            ],
            [
                'name' => 'Manual Deposit request',
                'code' => 'manual_deposit_request',
                'for' => 'Admin',
                'subject' => 'Got a request for Manual Deposit',
                'title' => 'Manual Deposit request',
                'salutation' => 'Hi Admin',
                'message_body' => 'The manual deposit request details:<br />[[txn]]<br />[[gateway_name]]<br />[[deposit_amount]]',
                'footer_body' => 'Regards, [[site_title]]',
            ],
            [
                'name' => 'Withdraw Request (Admin)',
                'code' => 'withdraw_request',
                'for' => 'Admin',
                'subject' => 'Got a Withdraw Request',
                'title' => 'Withdraw Request',
                'salutation' => 'Hi Admin',
                'message_body' => 'Withdraw Request details:<br />[[txn]]<br />[[method_name]]<br />[[withdraw_amount]]',
                'footer_body' => 'Regards, [[site_title]]',
            ],
            [
                'name' => 'Admin Forget Password',
                'code' => 'admin_forget_password',
                'for' => 'Admin',
                'subject' => 'Admin Forget Password',
                'title' => 'Admin Forget Password',
                'salutation' => 'Hi Admin',
                'message_body' => 'Please click the button below to reset your password',
                'button_level' => 'Password reset',
                'button_link' => '[[token]]',
                'footer_body' => 'Regards, [[site_title]]',
            ],
            [
                'name' => 'Contact Mail Send',
                'code' => 'contact_mail',
                'for' => 'Admin',
                'subject' => '[[subject]] for [[full_name]]',
                'title' => 'Inquiry from [[full_name]]',
                'salutation' => 'Hi Admin',
                'message_body' => '[[message]]<br><hr>Sender: [[full_name]] ([[email]])',
                'footer_body' => 'Inquiry recorded via [[site_url]]',
            ],
            [
                'name' => 'KYC Request',
                'code' => 'kyc_request',
                'for' => 'Admin',
                'subject' => 'KYC Verification Request - [[full_name]]',
                'title' => 'KYC Review Required',
                'salutation' => 'Hi Admin',
                'message_body' => 'A user has submitted KYC documents for review.<br><br>User: [[full_name]]<br>Email: [[email]]<br>Type: [[kyc_type]]',
                'footer_body' => 'Compliance Management System',
            ],
            [
                'name' => 'Support Ticket (Admin)',
                'code' => 'admin_support_ticket',
                'for' => 'Admin',
                'subject' => 'Support Ticket Update',
                'title' => 'Support Ticket',
                'salutation' => 'Hi Admin',
                'message_body' => 'Support Ticket:<br />[[title]]<br />[[message]]<br />Status: [[status]]',
                'footer_body' => 'Member Support System',
            ],
        ];

        foreach ($templates as $data) {
            EmailTemplate::updateOrCreate(
                ['code' => $data['code']],
                array_merge($data, [
                    'for' => $data['for'] ?? 'User',
                    'status' => 1,
                    'footer_status' => 1,
                    'bottom_status' => 0,
                    'banner' => null, 
                ])
            );
        }
    }
}
