INSERT INTO `bill_services` (`api_id`, `code`, `method`, `name`, `currency`, `country`, `country_code`, `provider_code`, `type`, `label`, `data`, `amount`, `min_amount`, `max_amount`, `charge`, `charge_type`, `status`) VALUES
(NULL, 'ATT', 'Manual', 'AT&T', 'USD', 'United States', 'US', 'manual', 'utility', '["Account Number"]', '{}', 0, 1.00, 5000.00, 0.00, 'percentage', 1),
(NULL, 'VRZ', 'Manual', 'Verizon', 'USD', 'United States', 'US', 'manual', 'utility', '["Account Number"]', '{}', 0, 1.00, 5000.00, 0.00, 'percentage', 1),
(NULL, 'TMB', 'Manual', 'T-Mobile', 'USD', 'United States', 'US', 'manual', 'utility', '["Account Number"]', '{}', 0, 1.00, 5000.00, 0.00, 'percentage', 1),
(NULL, 'XFNT', 'Manual', 'Comcast Xfinity', 'USD', 'United States', 'US', 'manual', 'utility', '["Account Number"]', '{}', 0, 5.00, 2000.00, 1.50, 'fixed', 1),
(NULL, 'DUKE', 'Manual', 'Duke Energy', 'USD', 'United States', 'US', 'manual', 'utility', '["Account Number"]', '{}', 0, 10.00, 3000.00, 0.00, 'percentage', 1),
(NULL, 'FPL', 'Manual', 'Florida Power & Light (FPL)', 'USD', 'United States', 'US', 'manual', 'utility', '["Account Number"]', '{}', 0, 10.00, 3000.00, 0.00, 'percentage', 1),
(NULL, 'AMWT', 'Manual', 'American Water', 'USD', 'United States', 'US', 'manual', 'utility', '["Account Number"]', '{}', 0, 5.00, 1000.00, 0.00, 'percentage', 1),
(NULL, 'STFM', 'Manual', 'State Farm', 'USD', 'United States', 'US', 'manual', 'insurance', '["Policy Number"]', '{}', 0, 20.00, 10000.00, 0.00, 'percentage', 1),
(NULL, 'GEICO', 'Manual', 'Geico', 'USD', 'United States', 'US', 'manual', 'insurance', '["Policy Number"]', '{}', 0, 20.00, 10000.00, 0.00, 'percentage', 1),
(NULL, 'PROG', 'Manual', 'Progressive', 'USD', 'United States', 'US', 'manual', 'insurance', '["Policy Number"]', '{}', 0, 20.00, 10000.00, 0.00, 'percentage', 1),
(NULL, 'WFCC', 'Manual', 'Wells Fargo Credit Card', 'USD', 'United States', 'US', 'manual', 'credit_card', '["Credit Card Number"]', '{}', 0, 1.00, 15000.00, 0.00, 'percentage', 1),
(NULL, 'CHCC', 'Manual', 'Chase Credit Card', 'USD', 'United States', 'US', 'manual', 'credit_card', '["Credit Card Number"]', '{}', 0, 1.00, 15000.00, 0.00, 'percentage', 1),
(NULL, 'BACC', 'Manual', 'Bank of America CC', 'USD', 'United States', 'US', 'manual', 'credit_card', '["Credit Card Number"]', '{}', 0, 1.00, 15000.00, 0.00, 'percentage', 1),
(NULL, 'CAP1', 'Manual', 'Capital One', 'USD', 'United States', 'US', 'manual', 'credit_card', '["Credit Card Number"]', '{}', 0, 1.00, 10000.00, 0.00, 'percentage', 1),
(NULL, 'SPECT', 'Manual', 'Spectrum', 'USD', 'United States', 'US', 'manual', 'utility', '["Account Number"]', '{}', 0, 5.00, 2000.00, 0.00, 'percentage', 1),
(NULL, 'NFLX', 'Manual', 'Netflix', 'USD', 'United States', 'US', 'manual', 'subscription', '["Email Address"]', '{}', 0, 1.00, 100.00, 0.00, 'percentage', 1),
(NULL, 'DISN', 'Manual', 'Disney+', 'USD', 'United States', 'US', 'manual', 'subscription', '["Email Address"]', '{}', 0, 1.00, 100.00, 0.00, 'percentage', 1),
(NULL, 'HULU', 'Manual', 'Hulu', 'USD', 'United States', 'US', 'manual', 'subscription', '["Email Address"]', '{}', 0, 1.00, 100.00, 0.00, 'percentage', 1),
(NULL, 'PINU', 'Manual', 'City of Pinellas Utilities', 'USD', 'United States', 'US', 'manual', 'utility', '["Account Number"]', '{}', 0, 5.00, 2000.00, 0.00, 'percentage', 1);
