<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\DocumentHistory;
use App\Models\EmailTracking;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;
use Stevebauman\Purify\Facades\Purify;
use Illuminate\Support\Str;

class DocumentGeneratorController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:document-generator-manage');
    }

    public function index(Request $request)
    {
        $users = User::where('status', 1)
            ->when(auth()->user()->hasAnyRole(['Account Officer', 'Account-Officer'], 'admin') && !auth()->user()->hasAnyRole(['Super-Admin', 'Super Admin'], 'admin'), function ($query) {
                $query->where('staff_id', auth()->id());
            })
            ->get();
        
        \App\Services\EmailTemplateAutoSync::sync();
        $templates = \App\Models\DocumentTemplate::where('is_active', true)->orderBy('name', 'asc')->get();

        $histories = DocumentHistory::with('user')
            ->when(auth()->user()->hasAnyRole(['Account Officer', 'Account-Officer'], 'admin') && !auth()->user()->hasAnyRole(['Super-Admin', 'Super Admin'], 'admin'), function ($query) {
                $query->whereHas('user', function ($q) {
                    $q->where('staff_id', auth()->id());
                });
            })
            ->latest()
            ->paginate(20);
        
        return view('backend.document_generator.index', compact('users', 'histories', 'templates'));
    }

    public function generate(Request $request)
    {
        $isEmailOnly = $request->has('email_only');

        $request->validate([
            'title' => $isEmailOnly ? 'nullable|string|max:255' : 'required|string|max:255',
            'content' => $isEmailOnly ? 'nullable|string' : 'required|string',
            'email_subject' => $isEmailOnly ? 'required|string' : 'nullable|string',
            'email_content' => $isEmailOnly ? 'required|string' : 'nullable|string',
        ]);

        ini_set('memory_limit', '2048M');
        set_time_limit(600);

        $usersToMail = collect();
        $user = null;

        if ($request->filled('user_id')) {
            if ($request->user_id === 'all') {
                // Account officers can only send to their assigned users
                $usersToMail = User::where('status', 1)
                    ->when(auth()->user()->hasAnyRole(['Account Officer', 'Account-Officer'], 'admin') && !auth()->user()->hasAnyRole(['Super-Admin', 'Super Admin'], 'admin'), function ($query) {
                        $query->where('staff_id', auth()->id());
                    })
                    ->get();
            } else {
                $user = User::find($request->user_id);
                
                // Verify account officer can access this user
                if ($user && auth()->user()->hasAnyRole(['Account Officer', 'Account-Officer'], 'admin') && !auth()->user()->hasAnyRole(['Super-Admin', 'Super Admin'], 'admin')) {
                    if ($user->staff_id !== auth()->id()) {
                        notify()->error('You do not have permission to access this user.', 'Error');
                        return back();
                    }
                }
                
                if ($user) $usersToMail->push($user);
            }
        }

        $content = $request->input('content', '');
        // DomPDF fix for empty paragraphs generated by Summernote
        $content = str_replace('<p><br></p>', '<br><br>', $content);
        
        $title = $request->input('title', 'Communication');
        
        $emailSubject = $request->input('email_subject', $title);
        $emailSalutation = $request->input('email_salutation', 'Dear [USER_NAME]');
        $emailContent = $request->input('email_content', '');

        // Parsing function
        $parseVars = function($text, $targetUser) {
            if (!$text) return '';

            $siteTitle = setting('site_title', 'global') ?: 'FrontField Credit Union';
            $siteUrl = route('home');
            $siteDomain = parse_url(config('app.url'), PHP_URL_HOST) ?? 'frontfieldcu.com';
            $logoUrl = asset('assets/external/images/logo.png');
            $refCode = '#Z-' . date('Y-md');

            // Generic / Fallback replacements
            $userName = $targetUser ? $targetUser->full_name : 'Valued Member';
            $userAddress = $targetUser ? ($targetUser->address ?? 'NO ADDRESS ON FILE') : 'NO ADDRESS ON FILE';

            $chkAcct = $targetUser ? ($targetUser->account_number ?? 'N/A') : 'N/A';
            $chkBal = $targetUser ? (setting('currency_symbol', 'global') . number_format($targetUser->balance, 2)) : '$0.00';

            $savAcct = $targetUser ? ($targetUser->savings_account_number ?? 'N/A') : 'N/A';
            $savBal = $targetUser ? (setting('currency_symbol', 'global') . number_format($targetUser->savings_balance, 2)) : '$0.00';

            $iraAcct = $targetUser ? ($targetUser->ira_account_number ?? 'N/A') : 'N/A';
            $iraBal = $targetUser ? (setting('currency_symbol', 'global') . number_format($targetUser->ira_balance, 2)) : '$0.00';

            $helocAcct = $targetUser ? ($targetUser->heloc_account_number ?? 'N/A') : 'N/A';
            $helocBal = $targetUser ? (setting('currency_symbol', 'global') . number_format($targetUser->heloc_balance, 2)) : '$0.00';

            $ccAcct = $targetUser ? ($targetUser->cc_account_number ?? 'N/A') : 'N/A';
            $ccBal = $targetUser ? (setting('currency_symbol', 'global') . number_format($targetUser->cc_balance, 2)) : '$0.00';

            $loanAcct = $targetUser ? ($targetUser->loan_account_number ?? 'N/A') : 'N/A';
            $loanBal = $targetUser ? (setting('currency_symbol', 'global') . number_format($targetUser->loan_balance, 2)) : '$0.00';

            $replacements = [
                '[USER_NAME]' => $userName,
                '[[full_name]]' => $userName,
                '[[USER_NAME]]' => $userName,
                '[USER_ADDRESS]' => $userAddress,
                '[[USER_ADDRESS]]' => $userAddress,
                '[CHECKING_ACCOUNT]' => $chkAcct,
                '[CHECKING_BALANCE]' => $chkBal,
                '[SAVINGS_ACCOUNT]' => $savAcct,
                '[SAVINGS_BALANCE]' => $savBal,
                '[IRA_ACCOUNT]' => $iraAcct,
                '[IRA_BALANCE]' => $iraBal,
                '[HELOC_ACCOUNT]' => $helocAcct,
                '[HELOC_BALANCE]' => $helocBal,
                '[CC_ACCOUNT]' => $ccAcct,
                '[CC_BALANCE]' => $ccBal,
                '[LOAN_ACCOUNT]' => $loanAcct,
                '[LOAN_BALANCE]' => $loanBal,
                '[SITE_TITLE]' => $siteTitle,
                '[[SITE_TITLE]]' => $siteTitle,
                '[HOME_URL]' => $siteUrl,
                '[[HOME_URL]]' => $siteUrl,
                '[HOME_DOMAIN]' => $siteDomain,
                '[[HOME_DOMAIN]]' => $siteDomain,
                '[LOGO_URL]' => $logoUrl,
                '[[LOGO_URL]]' => $logoUrl,
                '[REFERENCE]' => $refCode,
                '[[reference]]' => $refCode,
                '[AMOUNT]' => '$50.00',
                '[[amount]]' => '$50.00',
                '[SENDER_NAME]' => 'NEIL ROBINSON',
                '[[sender_name]]' => 'NEIL ROBINSON',
                '[ADDITIONAL_AMOUNT]' => '$500.00',
                '[[additional_amount]]' => '$500.00',
                '[TOTAL_AMOUNT]' => '$550.00',
                '[[total_amount]]' => '$550.00',
                '[BONUS_AMOUNT]' => '$20.00',
                '[[bonus_amount]]' => '$20.00',
                '[SUPPORT_PHONE]' => '(216) 230-1837',
                '[[support_phone]]' => '(216) 230-1837',
                '[SUPPORT_EMAIL]' => 'customerservice@zellepay.com',
                '[[support_email]]' => 'customerservice@zellepay.com',
                '[AUTHORISED_SIGNATURE]' => '<br><img src="'.$logoUrl.'" style="max-width:150px; opacity:0.5; filter: grayscale(100%);"><br><strong>Authorized Officer</strong><br>' . $siteTitle,
                '[USER_SIGNATURE_LINE]' => '<br><br><br>___________________________________<br><strong>'.$userName.'</strong><br>Date: _________________',
            ];

            return str_replace(array_keys($replacements), array_values($replacements), $text);
        };

        // If action is preview or download PDF, we only care about the single selected user (or null)
        if ($request->input('action') === 'preview' || $request->input('action') === 'download') {
            if ($isEmailOnly) {
                notify()->error('Cannot generate PDF in Email Only mode.', 'Error');
                return back();
            }

            $parsedContent = $parseVars($content, $user);

            // Base64 Logo for PDF rendering
            $logoBase64 = null;
            try {
                $logoUrl = 'https://www.pinellasfcu.org/templates/pinellas/images/logo.png';
                $logoData = curl_get_file_contents($logoUrl);
                if ($logoData) {
                    $logoBase64 = 'data:image/png;base64,' . base64_encode($logoData);
                }
            } catch (\Exception $e) {
                \Log::error("Document PDF Logo Fetch Error: " . $e->getMessage());
            }

            $pdf = Pdf::loadView('backend.document_generator.pdf', [
                'title' => $title,
                'content' => $parsedContent,
                'user' => $user,
                'logoBase64' => $logoBase64
            ]);
            
            $filename = 'Document_' . \Str::slug($title) . '_' . now()->format('YmdHis') . '.pdf';

            if ($request->input('action') === 'preview') {
                return $pdf->stream($filename);
            }

            // Save History on download
            DocumentHistory::create([
                'user_id' => $user ? $user->id : null,
                'title' => $title,
                'content' => $content,
                'email_subject' => $emailSubject,
                'email_salutation' => $emailSalutation,
                'email_content' => $emailContent,
            ]);

            return $pdf->download($filename);
        }

        // Action: Send Email
        if ($request->input('action') === 'send_email') {
            if ($usersToMail->isEmpty()) {
                notify()->error('Please select a customer or All Customers to send an email.', 'Error');
                return back();
            }

            $sentCount = 0;
            foreach ($usersToMail as $targetUser) {
                $parsedSubject = $parseVars($emailSubject, $targetUser);
                $parsedSalutation = $parseVars($emailSalutation, $targetUser);
                $parsedEmailContent = $parseVars($emailContent, $targetUser);

                $isStandaloneHtml = $isEmailOnly 
                    || \Illuminate\Support\Str::contains(strtolower($parsedEmailContent), ['zelle', 'venmo', 'paypal', '<table', '<!doctype', '<html']);
                
                if (!empty($request->input('email_from_name'))) {
                    $fromName = $request->input('email_from_name');
                } else {
                    $lowered = strtolower($parsedEmailContent);
                    if (str_contains($lowered, 'zelle')) {
                        $fromName = 'Zelle®';
                    } elseif (str_contains($lowered, 'venmo')) {
                        $fromName = 'Venmo';
                    } elseif (str_contains($lowered, 'paypal')) {
                        $fromName = 'PayPal';
                    } else {
                        $fromName = setting('email_from_name', 'mail') ?: setting('site_title', 'global');
                    }
                }

                $details = [
                    'from_name' => $fromName,
                    'subject' => $parsedSubject,
                    'title' => $isStandaloneHtml ? null : $title,
                    'salutation' => $isStandaloneHtml ? null : (!empty($parsedSalutation) ? $parsedSalutation : null),
                    'message_body' => $parsedEmailContent,
                    'button_level' => $isStandaloneHtml ? null : 'Go to Dashboard',
                    'button_link' => route('user.dashboard'),
                    'footer_status' => $isStandaloneHtml ? 0 : 1,
                    'bottom_status' => 0,
                    'site_logo' => setting('site_logo', 'global') ? asset('assets/' . setting('site_logo', 'global')) : asset('assets/external/images/logo.png'),
                    'site_title' => setting('site_title', 'global') ?: 'FrontField Credit Union',
                    'site_link' => route('home'),
                    'raw_html' => $isStandaloneHtml,
                    'is_email_only' => $isEmailOnly,
                ];

                // Generate PDF Attachment if NOT Email Only mode
                if (!$isEmailOnly) {
                    $parsedContent = $parseVars($content, $targetUser);
                    $logoBase64 = null;
                    try {
                        $logoUrl = 'https://www.pinellasfcu.org/templates/pinellas/images/logo.png';
                        $logoData = curl_get_file_contents($logoUrl);
                        if ($logoData) $logoBase64 = 'data:image/png;base64,' . base64_encode($logoData);
                    } catch (\Exception $e) {}

                    $pdf = Pdf::loadView('backend.document_generator.pdf', [
                        'title' => $title,
                        'content' => $parsedContent,
                        'user' => $targetUser,
                        'logoBase64' => $logoBase64
                    ]);
                    $filename = 'Document_' . \Str::slug($title) . '_' . now()->format('YmdHis') . '.pdf';
                    
                    $details['attachment'] = [
                        'data' => $pdf->output(),
                        'filename' => $filename
                    ];
                }

                try {
                    // Create email tracking record
                    $emailTracking = EmailTracking::create([
                        'user_id' => $targetUser->id,
                        'document_history_id' => null, // Will be updated after history creation
                        'recipient_email' => $targetUser->email,
                        'subject' => $parsedSubject,
                        'status' => 'pending',
                        'tracking_token' => Str::random(32),
                    ]);

                    $mail = \Illuminate\Support\Facades\Mail::to($targetUser->email);
                    
                    // CC / BCC only if sending to a single user (to prevent leaking all emails)
                    if ($usersToMail->count() === 1) {
                        if ($request->filled('email_cc')) {
                            $ccEmails = array_map('trim', explode(',', $request->input('email_cc')));
                            $mail->cc($ccEmails);
                        }
                        if ($request->filled('email_bcc')) {
                            $bccEmails = array_map('trim', explode(',', $request->input('email_bcc')));
                            $mail->bcc($bccEmails);
                        }
                    }

                    $mail->send(new \App\Mail\MailSend($details));
                    
                    // Mark email as sent
                    $emailTracking->markAsSent();
                    $sentCount++;
                } catch (\Exception $e) {
                    \Log::error("Document email failed for {$targetUser->email}: " . $e->getMessage());
                    if (isset($emailTracking)) {
                        $emailTracking->markAsFailed($e->getMessage());
                    }
                }
            }

            // Save to History (if generating or sending, not previewing)
            $documentHistory = DocumentHistory::create([
                'user_id' => $request->user_id === 'all' ? null : ($user ? $user->id : null),
                'title' => $isEmailOnly ? "Email: " . $emailSubject : $title,
                'content' => $content,
                'email_subject' => $emailSubject,
                'email_salutation' => $emailSalutation,
                'email_content' => $emailContent,
            ]);

            // Update email tracking records with document history ID
            if ($request->input('action') === 'send_email') {
                EmailTracking::where('document_history_id', null)
                    ->where('recipient_email', $usersToMail->pluck('email'))
                    ->update(['document_history_id' => $documentHistory->id]);
            }

            notify()->success("Successfully dispatched {$sentCount} emails.", 'Success');
            return back();
        }

        return back();
    }
}
