<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\DocumentHistory;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;

class DocumentGeneratorController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:document-generator-manage');
    }

    public function index(Request $request)
    {
        $users = User::where('status', 1)->get();
        $histories = DocumentHistory::with('user')->latest()->paginate(20);
        
        return view('backend.document_generator.index', compact('users', 'histories'));
    }

    public function generate(Request $request)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
        ]);

        ini_set('memory_limit', '2048M');
        set_time_limit(600);

        $user = null;
        if ($request->filled('user_id')) {
            $user = User::find($request->user_id);
        }

        $content = $request->input('content');
        // DomPDF fix for empty paragraphs generated by Summernote
        $content = str_replace('<p><br></p>', '<br><br>', $content);
        
        $title = $request->input('title');
        
        $emailSubject = $request->input('email_subject', $title);
        $emailSalutation = $request->input('email_salutation', 'Dear [USER_NAME]');
        $emailContent = $request->input('email_content', '');

        // Parsing function
        $parseVars = function($text) use ($user) {
            if (!$user) return $text;
            
            $text = str_replace('[USER_NAME]', $user->full_name, $text);
            $text = str_replace('[USER_ADDRESS]', $user->address ?? 'NO ADDRESS ON FILE', $text);
            
            // Checking
            $text = str_replace('[CHECKING_ACCOUNT]', $user->account_number ?? 'N/A', $text);
            $text = str_replace('[CHECKING_BALANCE]', setting('currency_symbol', 'global') . number_format($user->balance, 2), $text);
            
            // Savings
            $text = str_replace('[SAVINGS_ACCOUNT]', $user->savings_account_number ?? 'N/A', $text);
            $text = str_replace('[SAVINGS_BALANCE]', setting('currency_symbol', 'global') . number_format($user->savings_balance, 2), $text);
            
            // IRA
            $text = str_replace('[IRA_ACCOUNT]', $user->ira_account_number ?? 'N/A', $text);
            $text = str_replace('[IRA_BALANCE]', setting('currency_symbol', 'global') . number_format($user->ira_balance, 2), $text);
            
            // HELOC
            $text = str_replace('[HELOC_ACCOUNT]', $user->heloc_account_number ?? 'N/A', $text);
            $text = str_replace('[HELOC_BALANCE]', setting('currency_symbol', 'global') . number_format($user->heloc_balance, 2), $text);
            
            // CC
            $text = str_replace('[CC_ACCOUNT]', $user->cc_account_number ?? 'N/A', $text);
            $text = str_replace('[CC_BALANCE]', setting('currency_symbol', 'global') . number_format($user->cc_balance, 2), $text);
            
            // Loan
            $text = str_replace('[LOAN_ACCOUNT]', $user->loan_account_number ?? 'N/A', $text);
            $text = str_replace('[LOAN_BALANCE]', setting('currency_symbol', 'global') . number_format($user->loan_balance, 2), $text);
            
            return $text;
        };

        // Replace dynamic variables if user is selected
        $parsedContent = $parseVars($content);
        $parsedSubject = $parseVars($emailSubject);
        $parsedSalutation = $parseVars($emailSalutation);
        $parsedEmailContent = $parseVars($emailContent);

        // Base64 Logo for PDF rendering
        $logoBase64 = null;
        try {
            $logoUrl = 'https://www.pinellasfcu.org/templates/pinellas/images/logo.png';
            $logoData = curl_get_file_contents($logoUrl);
            if ($logoData) {
                $logoBase64 = 'data:image/png;base64,' . base64_encode($logoData);
            }
        } catch (\Exception $e) {
            \Log::error("Document PDF Logo Fetch Error: " . $e->getMessage());
        }

        $pdf = Pdf::loadView('backend.document_generator.pdf', [
            'title' => $title,
            'content' => $parsedContent,
            'user' => $user,
            'logoBase64' => $logoBase64
        ]);
        
        $filename = 'Document_' . \Str::slug($title) . '_' . now()->format('YmdHis') . '.pdf';

        if ($request->input('action') === 'preview') {
            return $pdf->stream($filename);
        }
        
        // Save to History (if generating or sending, not previewing)
        DocumentHistory::create([
            'user_id' => $user ? $user->id : null,
            'title' => $title,
            'content' => $content, // Save raw content so it acts as template
            'email_subject' => $emailSubject,
            'email_salutation' => $emailSalutation,
            'email_content' => $emailContent,
        ]);

        if ($request->input('action') === 'send_email' && $user && $request->has('send_email')) {
            $details = [
                'subject' => $parsedSubject,
                'title' => $title,
                'salutation' => $parsedSalutation,
                'message_body' => $parsedEmailContent,
                'button_level' => 'Go to Dashboard',
                'button_link' => route('user.dashboard'),
                'footer_status' => 1,
                'bottom_status' => 0,
                'site_logo' => setting('site_logo', 'global') ? asset('assets/' . setting('site_logo', 'global')) : null,
                'site_title' => setting('site_title', 'global'),
                'site_link' => route('home'),
                'attachment' => [
                    'data' => $pdf->output(),
                    'filename' => $filename
                ]
            ];

            try {
                $mail = \Illuminate\Support\Facades\Mail::to($user->email);
                
                if ($request->filled('email_cc')) {
                    $ccEmails = array_map('trim', explode(',', $request->input('email_cc')));
                    $mail->cc($ccEmails);
                }
                
                if ($request->filled('email_bcc')) {
                    $bccEmails = array_map('trim', explode(',', $request->input('email_bcc')));
                    $mail->bcc($bccEmails);
                }

                $mail->send(new \App\Mail\MailSend($details));
                notify()->success('Document has been successfully emailed to ' . safe($user->email), 'Success');
            } catch (\Exception $e) {
                \Log::error("Document email failed: " . $e->getMessage());
                notify()->error('Failed to email the document. Please check your mail settings.', 'Error');
            }

            return back();
        }

        return $pdf->download($filename);
    }
}
